name: Publish npm


on:
  release:
    types: [created]
jobs: 
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Use Node ${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install deps and build (with cache)
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --access public  
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
