name: Publish
on:
  release:
    types: [published]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Use Node ${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install deps and build (with cache)
        uses: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --access public  
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
